name: Continuous Delivery | Docker Hub

on:
  push:
    branches:
      - feat/add-codeowners-templates
      - soliton-stable

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t curiosity2023/soliton-ip-semi-bolt:latest --target bolt-ai-production .

      - name: Push Docker image
        run: docker push curiosity2023/soliton-ip-semi-bolt:latest
